export const PAYMENT_TYPES = {
    EFECTIVO: 'EFECTIVO',
    TRANSFERENCIA: 'TRANSFERENCIA',
    CHEQUE: 'CHEQUE',
    CREDITO: 'CREDITO',
    DEBITO: 'DEBITO'
}

export const PAYMENT_STATUS = {
    PENDIENTE: 'PENDIENTE',
    COMPLETADO: 'COMPLETADO',
    FALLIDO: 'FALLIDO',
    CANCELADO: 'CANCELADO',
    REEMBOLSADO: 'REEMBOLSADO'
}

export const CURRENCIES = {
    ARS: 'ARS',
    USD: 'USD'
}